### ISSUE TITLE
Handle redirection when trying to reach protected pages

### ISSUE THREAD

**Issue by michau-k** [EIP-SAM/SAM-Solution-Node-js#177]

**Comment by vuongc** [comment]
## issue
- Route is accessible when it should not be:
  - `/logs`
  - `/forgotten-password`
  - `/create-user`
  - `/create-group`
  - `/users` + red page
  - `/groups` + red page
  - `/save` (red page only)
  - `/create-save`
  - `/restore` + red page
  - `/create-restore` + blank page
  - `/admin-action` + red page (first time)

**Comment by vuongc** [comment]
The issues in the last comment should be fixed in branch #282
