### ISSUE TITLE
Fix and update dependencies

### ISSUE THREAD

**Issue by michau-k** [EIP-SAM/SAM-Solution-Node-js#189]

**Comment by vuongc** [comment]
- Upgrade react-bootstrap to latest version which fix most of the warming on browser
- `UNMET PEER DEPENDENCY react@15.3.1`,
  `UNMET PEER DEPENDENCY react-bootstrap@0.29.5`,
  `UNMET PEER DEPENDENCY react-dom@15.3.1` and 
  `UNMET PEER DEPENDENCY webpack@2.1.0-beta.22`cannot be removed only by updating all of them
