### ISSUE TITLE
Unknown routes are accessible and lead to a blank page

### ISSUE THREAD

**Issue by vuongc** [EIP-SAM/SAM-Solution-Node-js#284]
# Issue
- Unknown routes are accessible
- We then arrived at a blank page

**Comment by clairealmozinos** [comment]
@vuongc You should renamed the issue : the real problem is when a user tries to access a route that doesn't exist.

**Comment by vuongc** [comment]
## TODO
- [x] Create container
- [x] Create components
- [x] Display a page indicating that the user is accessing an unknown page
- [x] After x second, redirect to login/dashboard
