### ISSUE TITLE
Encapsulate windows package manager for node.js

### ISSUE THREAD

**Issue by clairealmozinos** [EIP-SAM/SAM-Solution-Node-js#402]
Encapsulate windows [`oneget`](/OneGet/oneget) package manager, to use it from node.js

**Comment by Grenadingue** [comment]
Final version uses [`chocolatey`](/chocolatey/choco) which overlaps and abstracts [`oneget`](/OneGet/oneget)

In abstraction order, from bottom to top, see [`chocolatey`](/chocolatey/choco), [`batch-pacapt`](/Grenadingue/batch-pacapt), [`node-pacapt`](/Grenadingue/node-pacapt) and [`SAM-Solution-Daemon-Client`](/EIP-SAM/SAM-Solution-Daemon-Client)
