### ISSUE TITLE
Link software by user webpage with Server API

### ISSUE THREAD

**Issue by clairealmozinos** [EIP-SAM/SAM-Solution-Node-js#435]
###TODO
- [x] table
- [x] actions
- [x] buttons

**Comment by BernardJeremy** [comment]
Duplicate with #54 ?

**Comment by clairealmozinos** [comment]
@BernardJeremy This issue is about to make software by user webpage dynamic with data coming from the server.

**Comment by BernardJeremy** [comment]
The issue's title wasn't saying that at all :P
