### ISSUE TITLE
Edit group name remove user from this group

### ISSUE THREAD

**Issue by clairealmozinos** [EIP-SAM/SAM-Solution-Node-js#480]
When a user rename a group, all the user from this group are not in this group anymore

**Comment by Grenadingue** [comment]
Hmm interesting, users and groups are supposed to be linked with their ids, so renaming a group should not have any effect on inner users

I don't remember a similar failing case during my tests. Can you provide some steps to reproduce to make this bug appear @clairealmozinos  ?

**Comment by clairealmozinos** [comment]
@Grenadingue 
1) Create group
2) Add user to the group in /users/create-user page
3) Rename the group

**Comment by clairealmozinos** [comment]
Doen't seem to appear anymore

**Comment by Grenadingue** [comment]
A random bug, great
