### ISSUE TITLE
Fix DateRange for Logs

### ISSUE THREAD

**Issue by michau-k** [EIP-SAM/SAM-Solution-Node-js#77]
Some weird behaviour when filtering logs by range, some logs being over the max date are fetched. Might be a timezone issue.

**Comment by vuongc** [comment]
This is just an image to show the bug:
<img width="1286" alt="screen shot 2016-07-18 at 9 56 16 am" src="https://cloud.githubusercontent.com/assets/6729188/16908698/f3a4d314-4ccd-11e6-8edf-8a5a11c96bbc.png">

**Comment by vuongc** [comment]
## Server side receive:

``` shell
Criteria are  { findOpts: 
   { force: 'true',
     afterDate: '2016-07-11T10:00:00.000Z',
     beforeDate: '2016-07-15T10:00:00.000Z' } }
Find options  { time: 
   { '$gte': 2016-07-11T10:00:00.000Z,
     '$lte': 2016-07-15T10:00:00.000Z } }
```

For range between `11/07/2016` to `14/07/2016`

Have to check into webapp

**Comment by vuongc** [comment]
It was a timezone conflict using Date module. Fix by using Moment module instead

**Comment by vuongc** [comment]
Done
